### ISSUE TITLE
Issues and fixes while deploying

### ISSUE THREAD

**Issue by DeepaliTandale** [aws-samples/aws-ibm-mq-adapter#4]
Hi, Below are the issues I saw when I was trying to deploy git code. Hopefully it helps.  

1) It only works for Nodev16, but if i update to Nodev20 deployment failed for me.   
2) npm install was needed before deployment, maybe if we can add this text in README.doc many users will find it useful. 
3) I had to comment out RUN pip install awscli --upgrade --user from DockerFile
4) I updated CLI, aws-cdk, python version to the latest since it was failing to move ahead. 
5) I had to move to cloud9 because Mac M1 is not supported to pull docker image. would be helpful, if we can mention this somewhere on the document (I struggled and started looking for different container image). 

specific to the text which lead to confusion, if we can edit that will be easy for future users. 
1) Issue -> _For statement Configure defaultVpcId with an existing vpc ID. If you're integrating to Amazon MQ, you also need to configure a hostedZone parameter._    
Fix -> Default VPC didn't work in my case, had to create a new one using the quip setup. 
2)  _"hostedZone": "fqdn-zone", // Optional: Route53 Zone (Public and Private) used for Amazon MQ integration_
Fix -> For me only private hosted zone worked. I checked code, since it was only accessing privatehostedZone, so had to create a private zone.

**Comment by rinaudjaws** [comment]
1. What error did you get when deploying? 
2. npm install not needed, please use `yarn install` a mentioned in the README.
3. Fixed broken dependency (https://github.com/aws/aws-cli/issues/8036)
4. Should be fixed with the AWS CLI `--no-build-isolation` flag (see issue above). 
5. M1 not supported by IBM MQ docker, will add limitation: https://integration-development.ideas.ibm.com/ideas/MESNS-I-369

Issues:
1. I'll add note that VPC should have at least private and public subnets.
2. Private zone won't work because code generates certificates (ACM). See https://github.com/aws-samples/aws-ibm-mq-adapter/blob/main/lib/mq-amazon-mq-stack.ts#L47. You can't create certificates with private zone.
